export default [
  {
    title: 'Era Uma Vez Em... Hollywood',
    year: 2019,
    rate: 7.6,
    genres: ['comédia', 'drama'],
    favorite: true,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BZDEzNWFjMDMtMWQ2NS00OWZjLWI4YTctNmRlM2JkZGYxM2Q5XkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
  },
  {
    title: 'Django Livre',
    year: 2012,
    rate: 8.5,
    genres: ['faroeste', 'drama'],
    favorite: true,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BZGVjNDhlYmQtMzZkMS00ZjkxLTg5Y2MtYzk4ZjI5NzBhMDJmXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
  },
  {
    title: 'Bastardos Inglórios',
    year: 2009,
    rate: 8.4,
    genres: ['aventura', 'drama', 'guerra'],
    favorite: true,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BM2M5YzVlMDctZWI2ZC00MjdlLWE1YzctMTQ5OGQ1NGJhZWMyXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
  },
  {
    title: 'Pulp Fiction - Tempo de Violência',
    year: 1994,
    rate: 8.9,
    genres: ['policial', 'drama'],
    favorite: true,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BN2RiMTA1ZGQtOTNhYi00MjQyLTk0MzAtMWE1OTM2NWUxNzBkXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
  },
  {
    title: 'Clube da Luta',
    year: 1999,
    rate: 8.8,
    genres: ['drama'],
    favorite: false,
    watched: false,
    image: 'https://m.media-amazon.com/images/M/MV5BNDVhNjJlZmMtODJhOS00OWE4LTgxMzAtNjVlMzI0ZjI0OTMzXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
  },
  {
    title: 'Forrest Gump: O Contador de Histórias',
    year: 1994,
    rate: 8.8,
    genres: ['drama', 'romance'],
    favorite: false,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BYWYwNWY0ZjMtYzUxZS00ODI3LTllNzctODNiNjhlNjcyNWM0XkEyXkFqcGdeQXVyMjcwMzM0OTI@._V1_.jpg',
  },
  {
    title: 'O Lobo de Wall Street',
    year: 2013,
    rate: 8.2,
    genres: ['biografia', 'comédia', 'policial'],
    favorite: false,
    watched: false,
    image: 'https://m.media-amazon.com/images/M/MV5BZTk1Y2ViODktYjc5Mi00MTQwLWI1ZjItODQwYmI1NDQzMDU0XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg',
  },
  {
    title: 'A Origem',
    year: 2010,
    rate: 8.8,
    genres: ['ação', 'aventura', 'ficção'],
    favorite: false,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BN2NiZDM5ZjQtNGJjNy00NzhmLWI1NzktZTgzYTkyZDFmYTg2XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
  },
  {
    title: 'Coringa',
    year: 2019,
    rate: 8.4,
    genres: ['policial', 'drama', 'suspense'],
    favorite: false,
    watched: false,
    image: 'https://m.media-amazon.com/images/M/MV5BZTk2YmY1OTMtN2NhYi00OGE4LWEwZWEtZDI4YWEyZWJmMWNmXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
  },
  {
    title: 'O Senhor dos Anéis: A Sociedade do Anel',
    year: 2001,
    rate: 8.8,
    genres: ['ação', 'drama', 'aventura'],
    favorite: true,
    watched: true,
    image: 'https://m.media-amazon.com/images/M/MV5BNDEyMzU0ODUtMTdjOS00Y2E2LWJlZmEtYmJjMmQ2NWZlNGQ1XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
  },
  {
    title: 'Parasita',
    year: 2019,
    rate: 8.5,
    genres: ['drama', 'suspense'],
    favorite: false,
    watched: false,
    image: 'https://m.media-amazon.com/images/M/MV5BNDhhZjkyNGItY2VmZi00NjJhLWI0MzMtZTBlMjhlNzE0NzNiXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg',
  },
];
